export const chordsData = [
    {
        key: 'C Ionian',
        I_IV_V_I: ['C Major: C - E - G', 'F Major: F - A - C', 'G Major: G - B - D'],
        I_iv_IV_V: ['C Major: C - E - G', 'A Minor: A - C - E', 'F Major: F - A - C', 'G Major: G - B - D'],
        I_ii_V_I: ['C Major: C - E - G', 'D Minor: D - F - A', 'G Major: G - B - D'],
        I_V_ii_IV: ['C Major: C - E - G', 'G Major: G - B - D', 'D Minor: D - F - A', 'F Major: F - A - C'],
        I_V_iii_IV: ['C Major: C - E - G', 'G Major: G - B - D', 'E Minor: E - G - B', 'F Major: F - A - C'],
        I_V_ii_V: ['C Major: C - E - G', 'G Major: G - B - D', 'D Minor: D - F - A', 'G Major: G - B - D'],
        I_V_IV_V: ['C Major: C - E - G', 'G Major: G - B - D', 'F Major: F - A - C', 'G Major: G - B - D'],
    },
    {
        key: 'F Ionian',
        I_IV_V_I: ['F Major: F - A - C', 'Bb Major: Bb - D - F', 'C Major: C - E - G'],
        I_iv_IV_V: ['F Major: F - A - C', 'D Minor: D - F - A', 'Bb Major: Bb - D - F', 'C Major: C - E - G'],
        I_ii_V_I: ['F Major: F - A - C', 'G Minor: G - Bb - D', 'C Major: C - E - G'],
        I_V_ii_IV: ['F Major: F - A - C', 'C Major: C - E - G', 'G Minor: G - Bb - D', 'Bb Major: Bb - D - F'],
        I_V_iii_IV: ['F Major: F - A - C', 'C Major: C - E - G', 'A Minor: A - C - E', 'Bb Major: Bb - D - F'],
        I_V_ii_V: ['F Major: F - A - C', 'C Major: C - E - G', 'G Minor: G - Bb - D', 'C Major: C - E - G'],
        I_V_IV_V: ['F Major: F - A - C', 'C Major: C - E - G', 'Bb Major: Bb - D - F', 'C Major: C - E - G'],
    },
    {
      key: 'Bb Ionian',
      I_IV_V_I: ['Bb Major: Bb - D - F', 'Eb Major: Eb - G - Bb', 'F Major: F - A - C'],
      I_iv_IV_V: ['Bb Major: Bb - D - F', 'G Minor: G - Bb - D', 'Eb Major: Eb - G - Bb', 'F Major: F - A - C'],
      I_ii_V_I: ['Bb Major: Bb - D - F', 'A Minor: A - C - E', 'F Major: F - A - C'],
      I_V_ii_IV: ['Bb Major: Bb - D - F', 'F Major: F - A - C', 'A Minor: A - C - E', 'Eb Major: Eb - G - Bb'],
      I_V_iii_IV: ['Bb Major: Bb - D - F', 'F Major: F - A - C', 'C Minor: C - Eb - G', 'Eb Major: Eb - G - Bb'],
      I_V_ii_V: ['Bb Major: Bb - D - F', 'F Major: F - A - C', 'A Minor: A - C - E', 'F Major: F - A - C'],
      I_V_IV_V: ['Bb Major: Bb - D - F', 'F Major: F - A - C', 'Eb Major: Eb - G - Bb', 'F Major: F - A - C'],
    },
    {
      key: 'Eb Ionian',
      I_IV_V_I: ['Eb Major: Eb - G - Bb', 'Ab Major: Ab - C - Eb', 'Bb Major: Bb - D - F'],
      I_iv_IV_V: ['Eb Major: Eb - G - Bb', 'C Minor: C - Eb - G', 'Ab Major: Ab - C - Eb', 'Bb Major: Bb - D - F'],
      I_ii_V_I: ['Eb Major: Eb - G - Bb', 'D Minor: D - F - A', 'Bb Major: Bb - D - F'],
      I_V_ii_IV: ['Eb Major: Eb - G - Bb', 'Bb Major: Bb - D - F', 'D Minor: D - F - A', 'Ab Major: Ab - C - Eb'],
      I_V_iii_IV: ['Eb Major: Eb - G - Bb', 'Bb Major: Bb - D - F', 'F Minor: F - Ab - C', 'Ab Major: Ab - C - Eb'],
      I_V_ii_V: ['Eb Major: Eb - G - Bb', 'Bb Major: Bb - D - F', 'D Minor: D - F - A', 'Bb Major: Bb - D - F'],
      I_V_IV_V: ['Eb Major: Eb - G - Bb', 'Bb Major: Bb - D - F', 'Ab Major: Ab - C - Eb', 'Bb Major: Bb - D - F'],
    },
    {
      key: 'Ab Ionian',
      I_IV_V_I: ['Ab Major: Ab - C - Eb', 'Db Major: Db - F - Ab', 'Eb Major: Eb - G - Bb'],
      I_iv_IV_V: ['Ab Major: Ab - C - Eb', 'F Minor: F - Ab - C', 'Db Major: Db - F - Ab', 'Eb Major: Eb - G - Bb'],
      I_ii_V_I: ['Ab Major: Ab - C - Eb', 'G Minor: G - Bb - D', 'Eb Major: Eb - G - Bb'],
      I_V_ii_IV: ['Ab Major: Ab - C - Eb', 'Eb Major: Eb - G - Bb', 'G Minor: G - Bb - D', 'Db Major: Db - F - Ab'],
      I_V_iii_IV: ['Ab Major: Ab - C - Eb', 'Eb Major: Eb - G - Bb', 'Bb Minor: Bb - Db - F', 'Db Major: Db - F - Ab'],
      I_V_ii_V: ['Ab Major: Ab - C - Eb', 'Eb Major: Eb - G - Bb', 'G Minor: G - Bb - D', 'Eb Major: Eb - G - Bb'],
      I_V_IV_V: ['Ab Major: Ab - C - Eb', 'Eb Major: Eb - G - Bb', 'Db Major: Db - F - Ab', 'Eb Major: Eb - G - Bb'],
    },
    {
      key: 'Db Ionian',
      I_IV_V_I: ['Db Major: Db - F - Ab', 'Gb Major: Gb - Bb - Db', 'Ab Major: Ab - C - Eb'],
      I_iv_IV_V: ['Db Major: Db - F - Ab', 'Bb Minor: Bb - Db - F', 'Gb Major: Gb - Bb - Db', 'Ab Major: Ab - C - Eb'],
      I_ii_V_I: ['Db Major: Db - F - Ab', 'C Minor: C - Eb - G', 'Ab Major: Ab - C - Eb'],
      I_V_ii_IV: ['Db Major: Db - F - Ab', 'Ab Major: Ab - C - Eb', 'C Minor: C - Eb - G', 'Gb Major: Gb - Bb - Db'],
      I_V_iii_IV: ['Db Major: Db - F - Ab', 'Ab Major: Ab - C - Eb', 'Eb Minor: Eb - Gb - Bb', 'Gb Major: Gb - Bb - Db'],
      I_V_ii_V: ['Db Major: Db - F - Ab', 'Ab Major: Ab - C - Eb', 'C Minor: C - Eb - G', 'Ab Major: Ab - C - Eb'],
      I_V_IV_V: ['Db Major: Db - F - Ab', 'Ab Major: Ab - C - Eb', 'Gb Major: Gb - Bb - Db', 'Ab Major: Ab - C - Eb'],
    },
    {
      key: 'G Ionian',
      I_IV_V_I: ['G Major: G - B - D', 'C Major: C - E - G', 'D Major: D - F# - A'],
      I_iv_IV_V: ['G Major: G - B - D', 'E Minor: E - G - B', 'C Major: C - E - G', 'D Major: D - F# - A'],
      I_ii_V_I: ['G Major: G - B - D', 'A Minor: A - C - E', 'D Major: D - F# - A'],
      I_V_ii_IV: ['G Major: G - B - D', 'D Major: D - F# - A', 'A Minor: A - C - E', 'C Major: C - E - G'],
      I_V_iii_IV: ['G Major: G - B - D', 'D Major: D - F# - A', 'B Minor: B - D - F#', 'C Major: C - E - G'],
      I_V_ii_V: ['G Major: G - B - D', 'D Major: D - F# - A', 'A Minor: A - C - E', 'D Major: D - F# - A'],
      I_V_IV_V: ['G Major: G - B - D', 'D Major: D - F# - A', 'C Major: C - E - G', 'D Major: D - F# - A'],
    },
    {
      key: 'D Ionian',
      I_IV_V_I: ['D Major: D - F# - A', 'G Major: G - B - D', 'A Major: A - C# - E'],
      I_iv_IV_V: ['D Major: D - F# - A', 'B Minor: B - D - F#', 'G Major: G - B - D', 'A Major: A - C# - E'],
      I_ii_V_I: ['D Major: D - F# - A', 'E Minor: E - G - B', 'A Major: A - C# - E'],
      I_V_vi_IV: ['D Major: D - F# - A', 'A Major: A - C# - E', 'B Minor: B - D - F#', 'G Major: G - B - D'],
    },
    {
      key: 'A Ionian',
      I_IV_V_I: ['A Major: A - C# - E', 'D Major: D - F# - A', 'E Major: E - G# - B'],
      I_iv_IV_V: ['A Major: A - C# - E', 'F# Minor: F# - A - C#', 'D Major: D - F# - A', 'E Major: E - G# - B'],
      I_ii_V_I: ['A Major: A - C# - E', 'B Minor: B - D - F#', 'E Major: E - G# - B'],
      I_V_vi_IV: ['A Major: A - C# - E', 'E Major: E - G# - B', 'F# Minor: F# - A - C#', 'D Major: D - F# - A'],
    },
    {
      key: 'E Ionian',
      I_IV_V_I: ['E Major: E - G# - B', 'A Major: A - C# - E', 'B Major: B - D# - F#'],
      I_iv_IV_V: ['E Major: E - G# - B', 'C# Minor: C# - E - G#', 'A Major: A - C# - E', 'B Major: B - D# - F#'],
      I_ii_V_I: ['E Major: E - G# - B', 'F# Minor: F# - A - C#', 'B Major: B - D# - F#'],
      I_V_vi_IV: ['E Major: E - G# - B', 'B Major: B - D# - F#', 'C# Minor: C# - E - G#', 'A Major: A - C# - E'],
    },
    {
      key: 'B Ionian',
      I_IV_V_I: ['B Major: B - D# - F#', 'E Major: E - G# - B', 'F# Major: F# - A# - C#'],
      I_iv_IV_V: ['B Major: B - D# - F#', 'G# Minor: G# - B - D#', 'E Major: E - G# - B', 'F# Major: F# - A# - C#'],
      I_ii_V_I: ['B Major: B - D# - F#', 'C# Minor: C# - E - G#', 'F# Major: F# - A# - C#'],
      I_V_vi_IV: ['B Major: B - D# - F#', 'F# Major: F# - A# - C#', 'G# Minor: G# - B - D#', 'E Major: E - G# - B'],
    },
    {
      key: 'F# Ionian',
      I_IV_V_I: ['F# Major: F# - A# - C#', 'B Major: B - D# - F#', 'C# Major: C# - E# - G#'],
      I_iv_IV_V: ['F# Major: F# - A# - C#', 'D# Minor: D# - F# - A#', 'B Major: B - D# - F#', 'C# Major: C# - E# - G#'],
      I_ii_V_I: ['F# Major: F# - A# - C#', 'G# Minor: G# - B - D#', 'C# Major: C# - E# - G#'],
      I_V_vi_IV: ['F# Major: F# - A# - C#', 'C# Major: C# - E# - G#', 'D# Minor: D# - F# - A#', 'B Major: B - D# - F#'],
    },
    {
      key: 'C# Ionian',
      I_IV_V_I: ['C# Major: C# - E# - G#', 'F# Major: F# - A# - C#', 'G# Major: G# - B# - D#'],
      I_iv_IV_V: ['C# Major: C# - E# - G#', 'A# Minor: A# - C# - E#', 'F# Major: F# - A# - C#', 'G# Major: G# - B# - D#'],
      I_ii_V_I: ['C# Major: C# - E# - G#', 'D# Minor: D# - F# - A#', 'G# Major: G# - B# - D#'],
      I_V_vi_IV: ['C# Major: C# - E# - G#', 'G# Major: G# - B# - D#', 'A# Minor: A# - C# - E#', 'F# Major: F# - A# - C#'],
    },
    {
      key: 'C Dorian',
      i_IV: ['C Minor: C - Eb - G', 'F Major: F - A - C'],
      i_v: ['C Minor: C - Eb - G', 'G Minor: G - Bb - D'],
      i_bVII_bVI: ['C Minor: C - Eb - G', 'Bb Major: Bb - D - F', 'Ab Major: Ab - C - Eb'],
      i_III_IV: ['C Minor: C - Eb - G', 'Eb Major: Eb - G - Bb', 'F Major: F - A - C'],
    },
    {
      key: 'F Dorian',
      i_IV: ['F Minor: F - Ab - C', 'Bb Major: Bb - D - F'],
      i_v: ['F Minor: F - Ab - C', 'C Minor: C - Eb - G'],
      i_bVII_bVI: ['F Minor: F - Ab - C', 'Eb Major: Eb - G - Bb', 'Db Major: Db - F - Ab'],
      i_III_iv: ['F Minor: F - Ab - C', 'Ab Major: Ab - C - Eb', 'Bb Major: Bb - D - F'],
    },
    {
      key: 'C Phrygian',
      i_II_i: ['C Minor: C - Eb - G', 'Db Major: Db - F - Ab', 'C Minor: C - Eb - G'],
      i_VII_VI_V: ['C Minor: C - Eb - G', 'Bb Major: Bb - D - F', 'Ab Major: Ab - C - Eb', 'G Major: G - B - D'],
      i_bII_bVII_bVI: ['C Minor: C - Eb - G', 'Db Major: Db - F - Ab', 'Bb Major: Bb - D - F', 'Ab Major: Ab - C - Eb'],
      i_III_bII_i: ['C Minor: C - Eb - G', 'Eb Major: Eb - G - Bb', 'Db Major: Db - F - Ab', 'C Minor: C - Eb - G'],
    },
    {
    key: 'C Lydian',
    I_II_I_V: ['C Major: C - E - G', 'D Major: D - F# - A', 'C Major: C - E - G', 'G Major: G - B - D'],
    I_II_vii_iii: ['C Major: C - E - G', 'D Major: D - F# - A', 'B Minor: B - D - F#', 'E Minor: E - G - B'],
    I_II_V_iii: ['C Major: C - E - G', 'D Major: D - F# - A', 'G Major: G - B - D', 'E Minor: E - G - B'],
    I_II_iv_I: ['C Major: C - E - G', 'D Major: D - F# - A', 'F# Minor: F# - A - C#', 'C Major: C - E - G'],
  },
  {
    key: 'C Mixolydian',
    I7_IV: ['C7: C - E - G - Bb', 'F Major: F - A - C'],
    I7_V7_IV_I7: ['C7: C - E - G - Bb', 'G7: G - B - D - F', 'F Major: F - A - C', 'C7: C - E - G - Bb'],
    I7_IV_V7: ['C7: C - E - G - Bb', 'F Major: F - A - C', 'G7: G - B - D - F'],
    I7_bVII_IV_V7: ['C7: C - E - G - Bb', 'Bb Major: Bb - D - F', 'F Major: F - A - C', 'G7: G - B - D - F'],
  },
  {
    key: 'C Aeolian',
    i_bVI_iv_V: ['C Minor: C - Eb - G', 'Ab Major: Ab - C - Eb', 'F Minor: F - Ab - C', 'G Major: G - B - D'],
    i_bVII_bVI_i: ['C Minor: C - Eb - G', 'Bb Major: Bb - D - F', 'Ab Major: Ab - C - Eb', 'C Minor: C - Eb - G'],
    i_iv_V_i: ['C Minor: C - Eb - G', 'F Minor: F - Ab - C', 'G Major: G - B - D', 'C Minor: C - Eb - G'],
    i_bVI_bVII_V7: ['C Minor: C - Eb - G', 'Ab Major: Ab - C - Eb', 'Bb Major: Bb - D - F', 'G7: G - B - D - F'],
    i_III_bVI_bVII: ['C Minor: C - Eb - G', 'Eb Major: Eb - G - Bb', 'Ab Major: Ab - C - Eb', 'Bb Major: Bb - D - F'],
    i_III_bVII_V: ['C Minor: C - Eb - G', 'Eb Major: Eb - G - Bb', 'Bb Major: Bb - D - F', 'G Major: G - B - D'],
  },
  {
    key: 'C Locrian',
    i7b5_bII_vi_bV_i7b5: ['C Minor 7b5: C - Eb - Gb - Bb', 'Db Major: Db - F - Ab', 'Ab Major: Ab - C - Eb', 'Gb Major: Gb - Bb - Db', 'C Minor 7b5: C - Eb - Gb - Bb'],
    i7b5_iii7_bII_bV: ['C Minor 7b5: C - Eb - Gb - Bb', 'Eb Minor 7: Eb - Gb - Bb - Db', 'Db Major: Db - F - Ab', 'Gb Major: Gb - Bb - Db'],
    i7b5_bII_bVII: ['C Minor 7b5: C - Eb - Gb - Bb', 'Db Major: Db - F - Ab', 'Bb Major: Bb - D - F'],
    i7b5_bII_bVI: ['C Minor 7b5: C - Eb - Gb - Bb', 'Db Major: Db - F - Ab', 'Ab Major: Ab - C - Eb'],
  },
  {
    key: 'C Melodic Minor',
    i_bVI_iv_V7: ['C Minor: C - Eb - G', 'Ab Major: Ab - C - Eb', 'F Minor: F - Ab - C', 'G7: G - B - D - F'],
    i7_II7_V7: ['C Minor 7: C - Eb - G - Bb', 'D Major 7: D - F# - A - C#', 'G7: G - B - D - F'],
    i_II7_V7: ['C Minor 7: C - Eb - G - Bb', 'D7: D - F# - A - C', 'G7: G - B - D - F'],
    i_III_vi_II7: ['C Minor: C - Eb - G', 'Eb Major: Eb - G - Bb', 'A Minor: A - C - E', 'D7: D - F# - A - C'],
  },
  {
    key: 'C Harmonic Minor',
    i_V7_i_bVI: ['C Minor: C - Eb - G', 'G7: G - B - D - F', 'C Minor: C - Eb - G', 'Ab Major: Ab - C - Eb'],
    i_iv_V7_i: ['C Minor: C - Eb - G', 'F Minor: F - Ab - C', 'G7: G - B - D - F', 'C Minor: C - Eb - G'],
    i_bVI_V7_i: ['C Minor: C - Eb - G', 'Ab Major: Ab - C - Eb', 'G7: G - B - D - F', 'C Minor: C - Eb - G'],
    i_III_bVI_V7: ['C Minor: C - Eb - G', 'Eb Major: Eb - G - Bb', 'Ab Major: Ab - C - Eb', 'G7: G - B - D - F'],
  },
  {
    key: 'C Maj Pentatonic',
    I_V_vi_IV: ['C Major: C - E - G', 'G Major: G - B - D', 'A Minor: A - C - E', 'F Major: F - A - C'],
    I_IV_V: ['C Major: C - E - G', 'F Major: F - A - C', 'G Major: G - B - D'],
    vi_IV_V_I: ['A Minor: A - C - E', 'F Major: F - A - C', 'G Major: G - B - D', 'C Major: C - E - G'],
    IV_I_V: ['F Major: F - A - C', 'C Major: C - E - G', 'G Major: G - B - D'],
    I7_IV7_V7: ['C Major 7: C - E - G - B', 'F Major 7: F - A - C - E', 'G Major 7: G - B - D - F#'],
  },
  {
    key: 'C Min Pentatonic',
    i7_iv7_V7: ['C Minor 7: C - Eb - G - Bb', 'F Minor 7: F - Ab - C - Eb', 'G7: G - B - D - F'],
    i_V_bVI_iv: ['C Minor: C - Eb - G', 'G Major: G - B - D', 'Ab Major: Ab - C - Eb', 'F Minor: F - Ab - C'],
    i_bVII_i: ['Bb Major: Bb - D - F', 'C Minor: C - Eb - G'],
    i_III_iv: ['Eb Major: Eb - G - Bb', 'F Major: F - A - C'],
  },
  ];